/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'MarkyMark' at '12/19/15 3:01 PM' with Gradle 2.2
 *
 * @author MarkyMark, @date 12/19/15 3:01 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
